apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpkg-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dpkg-backend
  template:
    metadata:
      labels:
        app: dpkg-backend
    spec:
      containers:
      - name: dpkg-backend
        image: arsenikki/dpkg-viewer-backend:1.0.7
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpkg-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dpkg-frontend
  template:
    metadata:
      labels:
        app: dpkg-frontend
    spec:
      containers:
      - name: dpkg-frontend
        image: arsenikki/dpkg-viewer-frontend:1.1.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000