apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dpkgviewer.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /api/upload
        backend:
          serviceName: dpkg-backend-clusterip
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dpkgviewer.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dpkg-frontend-clusterip
          servicePort: 80


            