apiVersion: v1
kind: Service
metadata:
  name: dpkg-backend-clusterip
spec:
  type: ClusterIP
  selector:
    app: dpkg-backend
  ports:
  - port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dpkg-frontend-clusterip
spec:
  type: ClusterIP
  selector:
    app: dpkg-frontend
  ports:
  - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dpkg-static-test-lb
spec:
  type: LoadBalancer
  selector:
    app: dpkg-static-test
  ports:
  - port: 80